# Generated by Django 5.2.1 on 2026-07-03 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('price', models.PositiveBigIntegerField(help_text='Price in virtual coins/credits')),
                ('image', models.CharField(help_text='Crate image URL', max_length=400)),
                ('openings', models.PositiveBigIntegerField(default=0, help_text='Times opened on source')),
                ('is_new', models.BooleanField(default=False)),
                ('xp', models.IntegerField(default=0)),
                ('sort_order', models.IntegerField(db_index=True, default=0)),
                ('opens', models.PositiveBigIntegerField(default=0, help_text='Local opens')),
            ],
            options={
                'ordering': ['sort_order', 'price', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=180)),
                ('weapon', models.CharField(blank=True, max_length=100)),
                ('finish', models.CharField(blank=True, max_length=140)),
                ('wear', models.CharField(blank=True, max_length=40)),
                ('chance', models.FloatField(help_text='Drop chance in percent')),
                ('price', models.PositiveBigIntegerField(help_text='Value in virtual coins')),
                ('rarity', models.CharField(blank=True, max_length=40)),
                ('color', models.CharField(blank=True, max_length=9)),
                ('image', models.CharField(max_length=400)),
                ('order', models.IntegerField(default=0)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.case')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drops', to='api.case')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drops', to='api.caseitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='caseitem',
            index=models.Index(fields=['price'], name='api_caseite_price_de5082_idx'),
        ),
    ]
