# Generated by Django 5.2.1 on 2026-07-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_player_daily_claimed_date_player_daily_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True),
        ),
    ]
