# Generated by Django 5.2.1 on 2026-07-06 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_player_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=60)),
                ('n_players', models.IntegerField(default=2)),
                ('case_ids', models.JSONField(default=list)),
                ('total_cost', models.BigIntegerField(default=0)),
                ('status', models.CharField(default='active', max_length=16)),
                ('paid', models.BooleanField(default=False)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='api.player')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
