# Generated by Django 5.2.1 on 2026-07-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_battle'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='pot',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battle',
            name='seats',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='battle',
            name='winner_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='status',
            field=models.CharField(default='waiting', max_length=16),
        ),
    ]
