# Generated by Django 5.2.1 on 2026-07-17 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_battle_pot_battle_seats_battle_winner_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openrecord',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='trade_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.CreateModel(
            name='WithdrawRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(blank=True, max_length=120)),
                ('trade_url', models.URLField(max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('sent', 'Yuborildi'), ('completed', 'Yakunlandi'), ('rejected', 'Rad etildi')], db_index=True, default='pending', max_length=16)),
                ('reject_reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraws', to='api.player')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraws', to='api.openrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
