# Generated by Django 5.2.1 on 2026-07-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_openrecord_is_locked_player_trade_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openrecord',
            name='disposition',
            field=models.CharField(blank=True, choices=[('sold', 'Sotilgan'), ('upgraded', 'Yangilashga ketgan'), ('contract', 'Kontraktga ketgan'), ('withdrawn', 'Chiqarilgan')], max_length=16),
        ),
        migrations.AddField(
            model_name='openrecord',
            name='source',
            field=models.CharField(blank=True, choices=[('case', 'Keys'), ('battle', 'Jang'), ('contract', 'Kontrakt'), ('upgrade', 'Yangilash'), ('shop', "Do'kon")], db_index=True, max_length=16),
        ),
        migrations.AddField(
            model_name='openrecord',
            name='steam_price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
