# Generated by Django 5.2.1 on 2026-07-17 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_openrecord_disposition_openrecord_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_chat_id', models.BigIntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('card_number', models.CharField(max_length=32)),
                ('card_holder', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('bonus_percent', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('uses', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopUpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_sum', models.BigIntegerField()),
                ('coins', models.BigIntegerField()),
                ('bonus_percent', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('waiting', 'Kutilmoqda'), ('connected', 'Aloqada'), ('paid', "To'landi"), ('closed', 'Yopilgan')], db_index=True, default='waiting', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topups', to='api.paymentadmin')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topups', to='api.player')),
                ('promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topups', to='api.promocode')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
