# Generated by Django 5.2.1 on 2026-07-17 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_paymentadmin_promocode_topuprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promos', to='api.case'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='kind',
            field=models.CharField(choices=[('bonus', "To'ldirish bonusi"), ('case', 'Bepul keys')], default='bonus', max_length=8),
        ),
        migrations.AddField(
            model_name='promocode',
            name='max_uses',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='FreeCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_grants', to='api.case')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_cases', to='api.player')),
                ('promo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='free_cases', to='api.promocode')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_redemptions', to='api.player')),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='api.promocode')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('promo', 'player'), name='uniq_promo_per_player')],
            },
        ),
    ]
