# Generated by Django 5.2.1 on 2026-07-18 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_promocode_case_promocode_kind_promocode_max_uses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drops', to='api.player'),
        ),
    ]
