# Generated by Django 5.2.1 on 2026-07-19 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_drop_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUpMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'Foydalanuvchi'), ('admin', 'Admin')], max_length=8)),
                ('text', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='topup/%Y/%m/')),
                ('read_by_user', models.BooleanField(default=False)),
                ('read_by_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.topuprequest')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
