# Generated by Django 5.2.1 on 2026-07-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_topupmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='avatars/%Y/%m/'),
        ),
    ]
