# Generated by Django 5.2.1 on 2026-07-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_player_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='daily_claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
