# Generated by Django 5.2.1 on 2026-07-19 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_player_daily_claimed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ban_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='player',
            name='is_banned',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=64)),
                ('action', models.CharField(db_index=True, max_length=48)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('target_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to='api.player')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
