# Generated by Django 5.2.1 on 2026-07-19 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_player_ban_reason_player_is_banned_adminaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ref_code',
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='player',
            name='ref_earned',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='ref_milestone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='ref_qualified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='api.player'),
        ),
        migrations.CreateModel(
            name='ReferralEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('join', "Do'st qo'shildi"), ('topup', "To'lov ulushi"), ('milestone', 'Bosqich')], max_length=12)),
                ('amount', models.BigIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('referred', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ref_generated', to='api.player')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ref_earnings', to='api.player')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
